-- //======================== Gen Tables SQL ========================// --
-- //======== comment eg. : yyyyMMdd gen_table ${table_name} ========// --

-- 20201203 gen_table sku_course
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_course', '课程表', 'sku_course_chapter', 'course_id', 'Course', 'crud', 'com.yi.project.course', 'course', 'course', '课程', 'yi', '1', '/', '{\"parentMenuId\":\"2000\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"课程管理\",\"treeCode\":\"\"}', 'admin', '2020-12-03 20:57:47', '', '2020-12-03 21:48:33', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_id', '课程编号', 'bigint(20) unsigned', 'Long', 'courseId', '1', '1', NULL, NULL, NULL, NULL, '1', 'EQ', 'input', '', 1, 'admin', '2020-12-03 20:57:47', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_name', '课程名称', 'varchar(50)', 'String', 'courseName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2, 'admin', '2020-12-03 20:57:47', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_type', '课程类型', 'text', 'String', 'courseType', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'select', 'sku_course_type', 3, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_info', '课程简介', 'varchar(255)', 'String', 'courseInfo', '0', '0', '1', '1', '1', '1', NULL, 'LIKE', 'textarea', '', 4, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_image', '课程图片', 'varchar(500)', 'String', 'courseImage', '0', '0', '1', '1', '1', '1', NULL, 'EQ', 'upload', '', 5, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_video', '课程视频', 'varchar(500)', 'String', 'courseVideo', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'upload', '', 6, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'user_id', '任课教师', 'bigint(20)', 'Long', 'userId', '0', '0', '1', '1', NULL, '1', '1', 'EQ', 'input', '', 7, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_by', '创建者ID', 'bigint(20)', 'Long', 'createBy', '0', '0', '1', '1', NULL, '1', NULL, 'EQ', 'input', '', 8, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', '1', '1', NULL, '1', NULL, 'EQ', 'datetime', '', 9, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志（0代表存在 2代表删除）', 'char(1)', 'String', 'delFlag', '0', '0', '1', '1', NULL, NULL, NULL, 'EQ', 'input', '', 10, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'textarea', '', 11, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:48:33');
-- 20201203 gen_table sku_course_chapter
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_course_chapter', '课程章节表', NULL, NULL, 'CourseChapter', 'crud', 'com.yi.project.course', 'course', 'chapter', '课程章节', 'yi', '1', '/', '{\"parentMenuId\":\"2000\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"课程管理\",\"treeCode\":\"\"}', 'admin', '2020-12-03 20:57:48', '', '2020-12-03 21:36:23', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'chapter_id', '章节编号，自增', 'bigint(20) unsigned', 'Long', 'chapterId', '1', '1', NULL, NULL, NULL, NULL, '1', 'EQ', 'input', '', 1, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:36:23');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'chapter_name', '章节名称', 'varchar(50)', 'String', 'chapterName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:36:23');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'chapter_info', '章节简介', 'text', 'String', 'chapterInfo', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'summernote', '', 3, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:36:23');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_id', '课程编号，外键', 'bigint(20)', 'Long', 'courseId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 4, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:36:23');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'publish', '发布标志（2否1是，未发布的资源学生不可见）', 'char(1)', 'String', 'publish', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'radio', 'sys_yes_no', 5, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:36:23');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_by', '创建者ID', 'bigint(20)', 'Long', 'createBy', '0', '0', NULL, '1', NULL, '1', NULL, 'EQ', 'input', '', 6, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:36:23');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, '1', '1', 'EQ', 'datetime', '', 7, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:36:23');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志（0代表存在 2代表删除）', 'char(1)', 'String', 'delFlag', '0', '0', '1', '1', NULL, NULL, NULL, 'EQ', 'input', '', 8, 'admin', '2020-12-03 20:57:48', NULL, '2020-12-03 21:36:23');
-- 20201203 gen_table sku_course_signin
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_course_signin', '上课签到表', NULL, NULL, 'CourseSignin', 'crud', 'com.yi.project.course', 'course', 'signin', '签到管理', 'yi', '1', '/', '{\"parentMenuId\":\"2003\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"上课管理\",\"treeCode\":\"\"}', 'admin', '2020-12-03 21:51:51', '', '2020-12-03 22:04:16', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'signin_id', '签到表编号', 'bigint(20)', 'Long', 'signinId', '1', '0', NULL, NULL, NULL, '1', NULL, 'EQ', 'input', '', 1, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'signin_name', '签到表名', 'varchar(50)', 'String', 'signinName', '0', '0', NULL, '1', '1', '1', '1', 'LIKE', 'input', '', 2, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_id', '课程', 'bigint(20)', 'Long', 'courseId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 3, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'chapter_id', '章节', 'bigint(20)', 'Long', 'chapterId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 4, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'start_time', '开始时间', 'datetime', 'Date', 'startTime', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'datetime', '', 5, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'end_time', '结束时间', 'datetime', 'Date', 'endTime', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'datetime', '', 6, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_by', '创建者', 'bigint(20)', 'Long', 'createBy', '0', '0', NULL, '1', NULL, '1', '1', 'EQ', 'input', '', 7, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, '1', '1', 'BETWEEN', 'datetime', '', 8, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志（0代表存在 2代表删除）', 'char(1)', 'String', 'delFlag', '0', '0', '1', '1', NULL, NULL, NULL, 'EQ', 'input', '', 9, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:04:16');
-- 20201203 gen_table sku_course_signin_record
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_course_signin_record', '学生签到表', NULL, NULL, 'CourseSigninRecord', 'crud', 'com.yi.project.course', 'course', 'signrecord', '学生签到记录', 'yi', '1', '/', '{\"parentMenuId\":\"2003\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"上课管理\",\"treeCode\":\"\"}', 'admin', '2020-12-03 21:51:51', '', '2020-12-03 22:04:58', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'record_id', '签到记录编号', 'bigint(20)', 'Long', 'recordId', '1', '0', NULL, NULL, NULL, '1', NULL, 'EQ', 'input', '', 1, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:14:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'signin_id', '签到表编号', 'bigint(20)', 'Long', 'signinId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 2, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:14:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'user_id', '学生', 'bigint(20)', 'Long', 'userId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 3, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:14:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '签到时间', 'datetime', 'Date', 'createTime', '0', '0', '1', '1', NULL, '1', '1', 'BETWEEN', 'datetime', '', 4, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:14:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志（0代表存在 2代表删除）', 'char(1)', 'String', 'delFlag', '0', '0', '1', '1', NULL, NULL, NULL, 'EQ', 'input', '', 5, 'admin', '2020-12-03 21:51:51', NULL, '2020-12-03 22:14:58');


-- 20201204 get_table sku_resource
INSERT INTO `skuman`.`gen_table` (`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_resource', '共享资源表', NULL, NULL, 'Resources', 'crud', 'course', 'course', 'resources', '资源管理', 'yi', '1', '/', '{\"parentMenuId\":\"2002\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"章节管理\",\"treeCode\":\"\"}', 'admin', '2020-12-03 21:28:12', '', '2020-12-04 22:51:46', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'resource_id', '资源编号', 'bigint(20) unsigned', 'Long', 'resourceId', '1', '1', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', '1', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'resource_name', '资源名称', 'varchar(50)', 'String', 'resourceName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', '2', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'resource_info', '资源简介', 'varchar(200)', 'String', 'resourceInfo', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'textarea', '', '3', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'resource_type', '资源类型', 'char(1)', 'String', 'resourceType', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', 'sku_resource_type', '4', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'resource_path', '资源路径', 'varchar(500)', 'String', 'resourcePath', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'upload', '', '5', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'businz_id', '业务ID', 'bigint(20)', 'Long', 'businzId', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'input', '', '6', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'businz_type', '业务类型', 'char(1)', 'String', 'businzType', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', 'sku_businz_type', '7', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'businz_tag', '业务标识', 'char(1)', 'String', 'businzTag', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', 'sku_businz_tag', '8', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_by', '创建者ID', 'bigint(20)', 'Long', 'createBy', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'input', '', '9', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, NULL, NULL, '1', NULL, 'LIKE', 'datetime', '', '10', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志', 'char(1)', 'String', 'delFlag', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', 'sys_yes_no', '11', 'admin', '2020-12-03 21:28:12', NULL, '2020-12-04 22:51:46');
-- 20201204 gen_table sku_topic
INSERT INTO `skuman`.`gen_table` (`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_topic', '学生话题表', NULL, NULL, 'Topic', 'crud', 'com.yi.project.course', 'course', 'topic', '学生话题', 'yi', '1', '/', '{\"parentMenuId\":\"2006\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"网络答疑\",\"treeCode\":\"\"}', 'admin', '2020-12-04 22:54:24', '', '2020-12-04 22:59:15', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'topic_id', '话题编号', 'bigint(20)', 'Long', 'topicId', '1', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', '1', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'topic_pid', '父问题编号', 'bigint(20)', 'Long', 'topicPid', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', '2', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'title', '标题', 'varchar(100)', 'String', 'title', '0', '0', NULL, '1', '1', '1', '1', 'LIKE', 'textarea', '', '3', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'content', '内容', 'text', 'String', 'content', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'summernote', '', '4', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_id', '课程编号', 'bigint(20)', 'Long', 'courseId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', '5', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'chapter_id', '所属章节', 'bigint(20)', 'Long', 'chapterId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', '6', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'user_id', '创建者ID', 'bigint(20)', 'Long', 'userId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', '7', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'user_type', '创建者类型（1、话题主；2、教师；3、学生）', 'char(1)', 'String', 'userType', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'select', 'sku_topic_user_type', '8', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', '1', NULL, NULL, '1', NULL, 'EQ', 'datetime', '', '9', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');
INSERT INTO `skuman`.`gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志', 'char(1)', 'String', 'delFlag', '0', '0', '1', NULL, '1', '1', '1', 'EQ', 'radio', 'sys_yes_no', '10', 'admin', '2020-12-04 22:54:24', NULL, '2020-12-04 22:59:15');


-- 20201205 gen_table sku_group_user
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_group_user', '学生班级表', NULL, NULL, 'GroupUser', 'crud', 'com.yi.project.course', 'course', 'groupuser', '班级学生', 'yi', '1', '/', '{\"parentMenuId\":\"2000\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"课程管理\",\"treeCode\":\"\"}', 'admin', '2020-12-05 15:16:56', '', '2020-12-05 15:25:09', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'group_user_id', '班级学生关联ID', 'bigint(20) unsigned', 'Long', 'groupUserId', '1', '1', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 1, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:25:09');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'group_id', '班级编号', 'bigint(20)', 'Long', 'groupId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 2, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:25:09');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'user_id', '学生id', 'bigint(20)', 'Long', 'userId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 3, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:25:09');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_by', '创建者ID', 'bigint(20)', 'Long', 'createBy', '0', '0', '1', '1', NULL, '1', '1', 'EQ', 'input', '', 4, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:25:09');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, '1', '1', 'BETWEEN', 'datetime', '', 5, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:25:09');
-- 20201205 gen_table sku_course_group
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_course_group', '课程班级表', 'sku_group_user', 'group_id', 'CourseGroup', 'sub', 'com.yi.project.course', 'course', 'group', '学生班级', 'yi', '1', '/', '{\"parentMenuId\":\"2000\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"课程管理\",\"treeCode\":\"\"}', 'admin', '2020-12-05 15:16:56', '', '2020-12-05 15:22:01', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'group_id', '班级编号，自增', 'bigint(20) unsigned', 'Long', 'groupId', '1', '1', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 1, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:22:01');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'group_name', '班级名称', 'varchar(30)', 'String', 'groupName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:22:01');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_id', '课程编号', 'bigint(20)', 'Long', 'courseId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:22:01');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'start_time', '班级生效时间', 'date', 'Date', 'startTime', '0', '0', NULL, '1', '1', '1', '1', 'BETWEEN', 'datetime', '', 4, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:22:01');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'end_time', '班级失效时间', 'date', 'Date', 'endTime', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'datetime', '', 5, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:22:01');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_by', '创建者ID', 'bigint(20)', 'Long', 'createBy', '0', '0', '1', '1', NULL, NULL, NULL, 'EQ', 'input', '', 6, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:22:01');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', '1', '1', NULL, NULL, '1', 'BETWEEN', 'datetime', '', 7, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:22:01');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志（0代表存在 2代表删除）', 'char(1)', 'String', 'delFlag', '0', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 8, 'admin', '2020-12-05 15:16:56', NULL, '2020-12-05 15:22:01');
-- 20201205 gen_table sku_homework
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_homework', '作业表', 'sku_homework_allocat', 'homework_id', 'Homework', 'sub', 'com.yi.project.course', 'course', 'homework', '作业管理', 'yi', '1', '/', '{\"parentMenuId\":\"2000\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"课程管理\",\"treeCode\":\"\"}', 'admin', '2020-12-05 15:25:59', '', '2020-12-05 15:36:24', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'homework_id', '作业编号', 'bigint(20) unsigned', 'Long', 'homeworkId', '1', '1', NULL, NULL, NULL, NULL, '1', 'EQ', 'input', '', 1, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'homework_name', '作业名', 'varchar(50)', 'String', 'homeworkName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'chapter_id', '章节编号', 'bigint(20)', 'Long', 'chapterId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'course_id', '课程编号', 'bigint(20)', 'Long', 'courseId', '0', '0', NULL, '1', NULL, '1', '1', 'EQ', 'input', '', 4, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'group_id', '布置给班级', 'bigint(20)', 'Long', 'groupId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 5, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'deadline', '截止时间', 'datetime', 'Date', 'deadline', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'datetime', '', 6, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'content', '作业内容', 'text', 'String', 'content', '0', '0', NULL, '1', '1', NULL, '1', 'EQ', 'summernote', '', 7, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'publish', '发布标志', 'char(1)', 'String', 'publish', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'select', 'sys_yes_no', 8, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_by', '创建者', 'bigint(20)', 'Long', 'createBy', '0', '0', NULL, '1', NULL, '1', NULL, 'EQ', 'input', '', 9, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, '1', NULL, 'EQ', 'datetime', '', 10, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志', 'char(1)', 'String', 'delFlag', '0', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 11, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:36:24');
-- 20201205 gen_table sku_homework_answer
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_homework_answer', '学生作业答案表', NULL, NULL, 'HomeworkAnswer', 'crud', 'com.yi.project.course', 'course', 'hanswer', '作业提交', 'yi', '1', '/', '{\"parentMenuId\":\"2000\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"课程管理\",\"treeCode\":\"\"}', 'admin', '2020-12-05 15:25:59', '', '2020-12-05 15:35:57', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'answer_id', '答案编号', 'bigint(20) unsigned', 'Long', 'answerId', '1', '1', NULL, NULL, NULL, NULL, '1', 'EQ', 'input', '', 1, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'homework_id', '作业编号', 'bigint(20)', 'Long', 'homeworkId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 2, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'group_id', '组编号', 'bigint(20)', 'Long', 'groupId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'user_id', '学生编号', 'bigint(20)', 'Long', 'userId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 4, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'submit_time', '提交时间', 'datetime', 'Date', 'submitTime', '0', '0', '1', '1', '1', '1', '1', 'BETWEEN', 'datetime', '', 5, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'answer_content', '作业内容', 'text', 'String', 'answerContent', '0', '0', '1', '1', '1', '1', NULL, 'EQ', 'summernote', '', 6, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'comment', '作业评语', 'text', 'String', 'comment', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'input', '', 7, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'score', '作业分数', 'int(11)', 'Long', 'score', '0', '0', NULL, '1', '1', '1', '1', 'BETWEEN', 'input', '', 8, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'excellent', '优秀', 'char(1)', 'String', 'excellent', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', 'sys_yes_no', 9, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'del_flag', '删除标志', 'char(1)', 'String', 'delFlag', '0', '0', '1', NULL, '1', NULL, NULL, 'EQ', 'input', '', 10, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:35:57');
-- 20201205 gen_table sku_homework_allocat
INSERT INTO `skuman`.`gen_table`(`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('sku_homework_allocat', '作业分配表', NULL, NULL, 'HomeworkAllocat', 'crud', 'com.yi.project.course', 'course', 'hallocat', '作业分配', 'yi', '1', '/', '{\"parentMenuId\":\"2000\",\"treeName\":\"\",\"treeParentCode\":\"\",\"parentMenuName\":\"课程管理\",\"treeCode\":\"\"}', 'admin', '2020-12-05 15:25:59', '', '2020-12-05 15:32:58', '');
SELECT @parentId := LAST_INSERT_ID();
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'allocat_id', '作业批次ID', 'bigint(20) unsigned', 'Long', 'allocatId', '1', '1', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 1, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'homework_id', '作业编号', 'bigint(20)', 'Long', 'homeworkId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 2, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'group_id', '分配组', 'bigint(20)', 'Long', 'groupId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'receive_count', '分发人数', 'int(11)', 'Long', 'receiveCount', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'input', '', 4, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'summit_count', '提交最后', 'int(11)', 'Long', 'summitCount', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'input', '', 5, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'update_by', '更新者', 'varchar(30)', 'String', 'updateBy', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'input', '', 6, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', '1', '1', 'BETWEEN', 'datetime', '', 7, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_by', '创建者ID', 'bigint(20)', 'Long', 'createBy', '0', '0', NULL, '1', NULL, '1', '1', 'EQ', 'input', '', 8, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');
INSERT INTO `skuman`.`gen_table_column`(`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, '1', '1', 'BETWEEN', 'datetime', '', 9, 'admin', '2020-12-05 15:25:59', NULL, '2020-12-05 15:32:58');


-- 20201212 sys_menu  增加菜单
INSERT INTO `skuman`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2074', '课程查看', '2008', '6', '#', 'menuItem', 'F', '0', 'course:course:show', '#', 'admin', '2020-12-07 22:47:40', '', NULL, '');

-- 20201215 sys_menu  修改“课程”为“课程管理”
INSERT INTO `skuman`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2008', '课程管理', '2000', '1', '/course/course', '', 'C', '0', 'course:course:view', '#', 'admin', '2020-12-06 23:02:30', '', NULL, '课程菜单');
-- 20201215 sys_menu  取消“网络答疑”的链接
INSERT INTO `skuman`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2006', '网络答疑', '0', '1', '', 'menuItem', 'C', '0', '', 'fa fa-comments', 'admin', '2020-12-01 22:28:58', 'admin', '2020-12-15 21:05:29', '');

-- 20201219 sku_course 增加一些课程数据

INSERT INTO `skuman`.`sku_course`(`course_id`, `course_name`, `course_type`, `course_info`, `course_image`, `course_video`, `user_id`, `create_by`, `create_time`, `del_flag`, `remark`) VALUES (2, '大学计算机基础3', '1', '测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦', 'http://localhost:8088/profile/upload/2020/12/06/1f995c58-52d2-4565-9c3d-0a52574fcf0e.jpg', 'http://localhost:8088/profile/upload/2020/12/06/11cc808d-40f3-46fe-a8e3-1ae8f4bd8820.mp4', 1, 1, '2020-12-06 23:29:38', '0', '测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦测试数据啦啦啦');
INSERT INTO `skuman`.`sku_course`(`course_id`, `course_name`, `course_type`, `course_info`, `course_image`, `course_video`, `user_id`, `create_by`, `create_time`, `del_flag`, `remark`) VALUES (3, '大学计算机基础2', '2', '定义和用法\r\nheight 属性指定视频播放器的高度。\r\n\r\n提示：规定视频的高度和宽度是一个好习惯。如果设置这些属性，在页面加载时会为视频预留出空间。如果没有设置这些属性，那么浏览器就无法预先确定视频的尺寸，这样就无法为视频保留合适的空间。结果是，在页面加载的过程中，其布局也会产生变化。\r\n\r\n提示：请勿通过 height 和 width 属性来缩放视频！通过 height 和 width 属性来缩小视频，只会迫使用户下载原始的视频（即使在页面上它看起来较小）。正确的方法是在网页上使用该视频前，使用软件对视频进行压缩。', 'http://localhost:8088/profile/upload/2020/12/07/4cad143c-413f-4167-9c5a-6e63327f38b6.jpg', '', 1, 1, '2020-12-07 21:04:24', '0', '定义和用法\r\nheight 属性指定视频播放器的高度。\r\n\r\n提示：规定视频的高度和宽度是一个好习惯。如果设置这些属性，在页面加载时会为视频预留出空间。如果没有设置这些属性，那么浏览器就无法预先确定视频的尺寸，这样就无法为视频保留合适的空间。结果是，在页面加载的过程中，其布局也会产生变化。\r\n\r\n提示：请勿通过 height 和 width 属性来缩放视频！通过 height 和 width 属性来缩小视频，只会迫使用户下载原始的视频（即使在页面上它看起来较小）。正确的方法是在网页上使用该视频前，使用软件对视频进行压缩。');
INSERT INTO `skuman`.`sku_course`(`course_id`, `course_name`, `course_type`, `course_info`, `course_image`, `course_video`, `user_id`, `create_by`, `create_time`, `del_flag`, `remark`) VALUES (4, '数据库设计', '1', '国内大厂目前对Python的需求，主要集中在策略、模型和算法类岗位。大量应用Python的典型包括Youtube、Dropbox、Quora、Google、Facebook，以及百度、腾讯、字节跳动、豆瓣、知乎、汽车之家、美团等。最近头条的朋友让我帮忙内推，给我一个岗位清单，一眼望过去，80%以上都是算法岗位！你猜Python人才的需求量有多大？\r\n\r\n作者：学无止境焉\r\n链接：https://zhuanlan.zhihu.com/p/313731716\r\n来源：知乎\r\n著作权归作者所有。商业转载请联系作', 'http://localhost:8088/profile/upload/2020/12/07/66064b3d-1a52-42b1-9ada-abfa2a41583a.jpg', '', 1, 1, '2020-12-07 21:06:28', '0', '国内大厂目前对Python的需求，主要集中在策略、模型和算法类岗位。大量应用Python的典型包括Youtube、Dropbox、Quora、Google、Facebook，以及百度、腾讯、字节跳动、豆瓣、知乎、汽车之家、美团等。最近头条的朋友让我帮忙内推，给我一个岗位清单，一眼望过去，80%以上都是算法岗位！你猜Python人才的需求量有多大？\r\n\r\n作者：学无止境焉\r\n链接：https://zhuanlan.zhihu.com/p/313731716\r\n来源：知乎\r\n著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。');
-- 20201219 sku_topic 增加一些话题数据
INSERT INTO `skuman`.`sku_topic`(`topic_id`, `topic_pid`, `title`, `content`, `course_id`, `chapter_id`, `user_id`, `user_type`, `create_time`, `del_flag`) VALUES (1, 0, '什么是计算机', '<p>啊手动阀的撒撒旦</p><p>啊手动阀的撒撒旦</p><p>啊手动阀的撒撒旦</p><table class=\"table table-bordered\"><tbody><tr><td>1212</td></tr><tr><td>12</td></tr><tr><td>12</td></tr></tbody></table><p><br></p>', 2, NULL, 1, '1', '2020-12-17 21:37:41', '0');
INSERT INTO `skuman`.`sku_topic`(`topic_id`, `topic_pid`, `title`, `content`, `course_id`, `chapter_id`, `user_id`, `user_type`, `create_time`, `del_flag`) VALUES (2, 0, '看空间', '<p>121212</p>', 4, NULL, 1, '1', '2020-12-17 22:00:14', '0');
INSERT INTO `skuman`.`sku_topic`(`topic_id`, `topic_pid`, `title`, `content`, `course_id`, `chapter_id`, `user_id`, `user_type`, `create_time`, `del_flag`) VALUES (3, 0, '返回', '<p>烦得很的</p>', 4, NULL, 1, '1', '2020-12-17 22:29:06', '0');
INSERT INTO `skuman`.`sku_topic`(`topic_id`, `topic_pid`, `title`, `content`, `course_id`, `chapter_id`, `user_id`, `user_type`, `create_time`, `del_flag`) VALUES (4, 0, '代付', '<p>的话</p>', 2, NULL, 1, '1', '2020-12-17 22:29:14', '0');
INSERT INTO `skuman`.`sku_topic`(`topic_id`, `topic_pid`, `title`, `content`, `course_id`, `chapter_id`, `user_id`, `user_type`, `create_time`, `del_flag`) VALUES (5, 0, '十大歌手', '<p>三个<img src=\"http://localhost:8088/profile/upload/2020/12/17/6a4191e8-113c-4717-8b00-929d6d7f3320.JPG\" style=\"width: 448px;\"></p>', 2, NULL, 1, '1', '2020-12-17 22:29:39', '0');
INSERT INTO `skuman`.`sku_topic`(`topic_id`, `topic_pid`, `title`, `content`, `course_id`, `chapter_id`, `user_id`, `user_type`, `create_time`, `del_flag`) VALUES (6, 1, '什么是计算机', '<p>啊沙发上撒旦大神阿斯蒂啊</p><p>啊沙发上撒旦大神阿斯蒂啊</p><p>啊沙发上撒旦大神阿斯蒂啊</p><p>啊沙发上撒旦大神阿斯蒂啊<br></p>', 2, NULL, 1, '2', '2020-12-19 14:34:24', '0');
INSERT INTO `skuman`.`sku_topic`(`topic_id`, `topic_pid`, `title`, `content`, `course_id`, `chapter_id`, `user_id`, `user_type`, `create_time`, `del_flag`) VALUES (7, 0, '案说法撒旦', '<p>撒地方撒旦士大夫是扽</p>', 2, NULL, 1, '1', '2020-12-19 14:37:44', '0');
INSERT INTO `skuman`.`sku_topic`(`topic_id`, `topic_pid`, `title`, `content`, `course_id`, `chapter_id`, `user_id`, `user_type`, `create_time`, `del_flag`) VALUES (8, 1, '什么是计算机', '<p>阿斯顿发顺丰</p><p><img src=\"http://localhost:8088/profile/upload/2020/12/19/897a92ad-158e-438a-9b99-85a4ae0dfb16.JPG\" style=\"width: 615px;\"><br></p>', 2, NULL, 1, '2', '2020-12-19 15:23:18', '0');
-- 20201227 sys_menu 菜单,修改章节的父菜单为 课程
UPDATE `skuman`.`sys_menu` SET `menu_name` = '课程章节', `parent_id` = 2000, `order_num` = 1, `url` = '/course/course/courseList', `target` = 'menuItem', `menu_type` = 'C', `visible` = '0', `perms` = 'course:chapter:view', `icon` = '#', `create_by` = 'admin', `create_time` = '2020-12-06 23:02:30', `update_by` = 'admin', `update_time` = '2020-12-09 22:02:00', `remark` = '课程章节菜单' WHERE `menu_id` = 2014;
UPDATE `skuman`.`sys_menu` SET `menu_name` = '课程章节查询', `parent_id` = 2008, `order_num` = 1, `url` = '#', `target` = '', `menu_type` = 'F', `visible` = '0', `perms` = 'course:chapter:list', `icon` = '#', `create_by` = 'admin', `create_time` = '2020-12-06 23:02:30', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `menu_id` = 2015;
UPDATE `skuman`.`sys_menu` SET `menu_name` = '课程章节新增', `parent_id` = 2008, `order_num` = 2, `url` = '#', `target` = '', `menu_type` = 'F', `visible` = '0', `perms` = 'course:chapter:add', `icon` = '#', `create_by` = 'admin', `create_time` = '2020-12-06 23:02:30', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `menu_id` = 2016;
UPDATE `skuman`.`sys_menu` SET `menu_name` = '课程章节修改', `parent_id` = 2008, `order_num` = 3, `url` = '#', `target` = '', `menu_type` = 'F', `visible` = '0', `perms` = 'course:chapter:edit', `icon` = '#', `create_by` = 'admin', `create_time` = '2020-12-06 23:02:30', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `menu_id` = 2017;
UPDATE `skuman`.`sys_menu` SET `menu_name` = '课程章节删除', `parent_id` = 2008, `order_num` = 4, `url` = '#', `target` = '', `menu_type` = 'F', `visible` = '0', `perms` = 'course:chapter:remove', `icon` = '#', `create_by` = 'admin', `create_time` = '2020-12-06 23:02:30', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `menu_id` = 2018;
UPDATE `skuman`.`sys_menu` SET `menu_name` = '课程章节导出', `parent_id` = 2008, `order_num` = 5, `url` = '#', `target` = '', `menu_type` = 'F', `visible` = '0', `perms` = 'course:chapter:export', `icon` = '#', `create_by` = 'admin', `create_time` = '2020-12-06 23:02:30', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `menu_id` = 2019;

-- 20201227 sys_role_menu  增加教师和学生的权限

INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 1);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 107);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 1035);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2000);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2003);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2006);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2008);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2009);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2010);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2011);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2012);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2014);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2015);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2016);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2017);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2018);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2020);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2021);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2023);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2024);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2026);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2027);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2032);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2033);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2034);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2035);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2038);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2039);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2040);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2041);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2042);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (100, 2074);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 1);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 107);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 1035);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2000);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2003);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2008);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2009);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2014);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2015);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2020);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2021);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2026);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2027);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2028);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2032);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2033);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2034);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2038);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2039);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2056);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2057);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2068);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2069);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2070);
INSERT INTO `skuman`.`sys_role_menu`(`role_id`, `menu_id`) VALUES (101, 2074);
-- sys_menu 新增学生菜单
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2084, '我的签到', 0, 1, '#', 'menuItem', 'M', '0', NULL, 'fa fa-address-card-o', 'admin', '2020-12-28 22:51:14', '', NULL, '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2085, '签到列表', 2084, 1, '/course/signin', 'menuItem', 'C', '0', 'course:signin:view', 'fa fa-address-book', 'admin', '2020-12-28 22:52:23', 'admin', '2020-12-28 23:08:14', '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2086, '签到查询', 2085, 1, '#', 'menuItem', 'F', '0', 'course:signin:list', '#', 'admin', '2020-12-28 22:53:42', '', NULL, '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2087, '签到记录', 2084, 2, '/course/signrecord', 'menuItem', 'C', '0', 'course:signrecord:view', 'fa fa-address-book-o', 'admin', '2020-12-28 22:54:36', 'admin', '2020-12-28 23:08:25', '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2088, '签到记录查询', 2087, 1, '#', 'menuItem', 'F', '0', 'course:signrecord:list', '#', 'admin', '2020-12-28 22:55:45', '', NULL, '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2089, '签到记录新增', 2087, 2, '#', 'menuItem', 'F', '0', 'course:signrecord:add', '#', 'admin', '2020-12-28 22:56:13', '', NULL, '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2090, '我的课程', 0, 1, '/course/course', 'menuItem', 'C', '0', 'course:course:view', 'fa fa-book', 'admin', '2020-12-28 22:57:15', 'admin', '2020-12-28 23:01:21', '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2091, '我的课程', 2090, 1, '/course/course', 'menuItem', 'C', '0', 'course:course:list', '#', 'admin', '2020-12-28 23:11:19', 'admin', '2020-12-28 23:11:37', '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2092, '我的资源', 2090, 2, '/system/resources', 'menuItem', 'C', '0', 'system:resources:view', '#', 'admin', '2020-12-28 23:11:55', 'admin', '2020-12-28 23:12:56', '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2093, '课程章节', 2091, 1, '/course/course/courseList', 'menuItem', 'C', '1', 'course:chapter:view', '#', 'admin', '2020-12-28 23:13:38', 'admin', '2020-12-28 23:14:18', '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2094, '课程查询', 2091, 1, '#', 'menuItem', 'F', '0', 'course:course:list', '#', 'admin', '2020-12-28 23:15:00', '', NULL, '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2095, '课程查看', 2091, 2, '#', 'menuItem', 'F', '0', 'course:course:view', '#', 'admin', '2020-12-28 23:15:32', '', NULL, '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2096, '课程章节查询', 2093, 1, '#', 'menuItem', 'F', '0', 'course:chapter:list', '#', 'admin', '2020-12-28 23:16:22', 'admin', '2020-12-28 23:16:42', '');
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2097, '资源管理查询', 2092, 1, '#', 'menuItem', 'F', '0', 'system:resources:list', '#', 'admin', '2020-12-28 23:19:12', '', NULL, '');

-- 增加学生的课程菜单
INSERT INTO `skuman`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `url`, `target`, `menu_type`, `visible`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2098, '我的作业查询', 2068, 1, '#', 'menuItem', 'F', '0', 'course:homework:list', '#', 'admin', '2021-01-01 21:20:02', '', NULL, '');


